class Appointment {
  final int? id;
  final int userId;
  final String serviceType;
  final String date; // YYYY-MM-DD
  final String time; // HH:mm
  final String status; // 'pending', 'approved', 'rejected', 'completed'
  final String details; // Generated by AI
  final String? description; // User provided or AI enhanced

  Appointment({
    this.id,
    required this.userId,
    required this.serviceType,
    required this.date,
    required this.time,
    required this.status,
    required this.details,
    this.description,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'user_id': userId,
      'service_type': serviceType,
      'date': date,
      'time': time,
      'status': status,
      'details': details,
      'description': description,
    };
  }

  factory Appointment.fromMap(Map<String, dynamic> map) {
    return Appointment(
      id: map['id'],
      userId: map['user_id'],
      serviceType: map['service_type'],
      date: map['date'],
      time: map['time'],
      status: map['status'],
      details: map['details'],
      description: map['description'],
    );
  }
}
